#travis configuration for coverage testing 
# M A Chatterjee 2018-07-05

language: node_js
node_js:
  - "14"
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
cache: npm
script:
  - npm run test
